In [1]:
import numpy as np

In [2]:
new_array = np.random.randint(1,100,20)

In [4]:
new_array

array([93, 94, 37, 34, 15, 69, 75, 76, 11, 83, 25, 34, 50, 62, 50, 51, 10,
       18, 58, 64], dtype=int32)

In [5]:
new_array > 25

array([ True,  True,  True,  True, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True, False, False,
        True,  True])

In [6]:
new_array [ new_array > 25 ]

array([93, 94, 37, 34, 69, 75, 76, 83, 34, 50, 62, 50, 51, 58, 64],
      dtype=int32)

In [7]:
new_array [ new_array < 25 ]

array([15, 11, 10, 18], dtype=int32)

In [13]:
matrix_array = np.array([[10,20],[20,30],[30,40]])

In [14]:
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [15]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [16]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [26]:
random_array = np.random.random((6,1))

In [27]:
random_array

array([[0.45612599],
       [0.86166869],
       [0.77690889],
       [0.04249174],
       [0.34672066],
       [0.08735519]])

In [28]:
random_array.shape

(6, 1)

In [33]:
random_array.reshape(3,2)

array([[0.45612599, 0.86166869],
       [0.77690889, 0.04249174],
       [0.34672066, 0.08735519]])

In [34]:
# z- score

In [37]:
data = np.array ([10,12,37,25,100,120])

In [38]:
data

array([ 10,  12,  37,  25, 100, 120])

In [41]:
mean = np.mean(data)

In [42]:
mean

np.float64(50.666666666666664)

In [45]:
data.sum() / len(data)

np.float64(50.666666666666664)

In [60]:
std = np.std(data)

In [49]:
std

np.float64(43.27303497047042)

In [48]:
z_score = (data-mean) / std

In [50]:
z_score

array([-0.93976923, -0.89355107, -0.31582408, -0.59313304,  1.14004792,
        1.6022295 ])

In [53]:
data[z_score > 1]

array([100, 120])

In [54]:
# math equations 

In [55]:
# 2x + 3y = 8 and 5x + 7y = 19

In [56]:
# coefficient

In [59]:
A = np.array([[2,3],[5,7]])

In [61]:
# constant

In [62]:
B = np.array([8,19])

In [64]:
solution = np.linalg.solve(A,B)

In [65]:
solution

array([1., 2.])